# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9b2e2f6e1db43c64eacd294ebc2e454cae40e4fd32913e2692fdaf63ce0019cb2c4bae0f9fb8806f70326c6280b8748c4d7192691129f1ecc51647316c5f7255

test:
  secret_key_base: 5b6fd7fc976e662a6ca3862783fcd283bd9dc54b6edcb9be68f6e978e781ab990e5d51c0b4788e87d528f1bb24fba7bb46a085b31635382ce93885cf1b6c68a2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
